"""create users, requests, episodes, assignments, status history

Revision ID: 752fdccf4144
Revises: 
Create Date: 2026-10-01 10:41:39.268865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic
revision: str = '752fdccf4144'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.String(length=64), nullable=False),
    sa.Column('robot_id', sa.String(length=64), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=False),
    sa.Column('quality', sa.Enum('good', 'usable', 'bad', name='episode_quality'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds > 0', name='ck_episodes_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_episode_id'), 'episodes', ['episode_id'], unique=True)
    op.create_index('ix_episodes_quality', 'episodes', ['quality'], unique=False)
    op.create_index('ix_episodes_recorded_at', 'episodes', ['recorded_at'], unique=False)
    op.create_index('ix_episodes_robot_id', 'episodes', ['robot_id'], unique=False)
    op.create_index('ix_episodes_task_name', 'episodes', ['task_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'operator', 'admin', name='user_role'), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('episodes_requested', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'in_progress', 'delivered', 'accepted', 'rejected', name='request_status'), server_default='submitted', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('episodes_requested > 0', name='ck_requests_episodes_requested_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_client_id', 'requests', ['client_id'], unique=False)
    op.create_index('ix_requests_deadline', 'requests', ['deadline'], unique=False)
    op.create_index('ix_requests_status', 'requests', ['status'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_episode_id'), 'assignments', ['episode_id'], unique=True)
    op.create_index(op.f('ix_assignments_request_id'), 'assignments', ['request_id'], unique=False)
    op.create_table('request_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('submitted', 'in_progress', 'delivered', 'accepted', 'rejected', name='request_status'), nullable=True),
    sa.Column('to_status', sa.Enum('submitted', 'in_progress', 'delivered', 'accepted', 'rejected', name='request_status'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_status_history_changed_at', 'request_status_history', ['changed_at'], unique=False)
    op.create_index('ix_request_status_history_request_id', 'request_status_history', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_status_history_request_id', table_name='request_status_history')
    op.drop_index('ix_request_status_history_changed_at', table_name='request_status_history')
    op.drop_table('request_status_history')
    op.drop_index(op.f('ix_assignments_request_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_episode_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_requests_status', table_name='requests')
    op.drop_index('ix_requests_deadline', table_name='requests')
    op.drop_index('ix_requests_client_id', table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_episodes_task_name', table_name='episodes')
    op.drop_index('ix_episodes_robot_id', table_name='episodes')
    op.drop_index('ix_episodes_recorded_at', table_name='episodes')
    op.drop_index('ix_episodes_quality', table_name='episodes')
    op.drop_index(op.f('ix_episodes_episode_id'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###

    # drop_table does not remove PG enum types; clean them up explicitly so a
    # downgrade -> upgrade cycle works from a clean state.
    postgresql.ENUM(  # type: ignore[attr-defined]
        name="request_status"
    ).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(  # type: ignore[attr-defined]
        name="episode_quality"
    ).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(  # type: ignore[attr-defined]
        name="user_role"
    ).drop(op.get_bind(), checkfirst=True)
